spring.application.name=VesselTracker
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hamza.laabail.uhp@gmail.com
spring.mail.password=sehfnikcrnzhpomq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mvc.async.request-timeout=60000
spring.mail.properties.mail.debug=true
app.api.key=qxwQtKsWKFlnhnPfyblcKjHKN
app.mail.from=hamza.laabail.uhp@gmail.com